### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by dashohoxha** [BRL-CAD/brlcad-docs#29]
When it was on my namespace (`dashohoxha`) it made sense to call it `brlcad-docs`.
But now that it is on `BRL-CAD` it would make more sense to call it just `docs` or `antora-docs`.
However, after transferring the repo, I don't have access to its **Settings** anymore, so I can't do it myself.

**Comment by brlcad** [comment]
I thought about that when the repo was first transferred, but I think it's fine for the foreseeable future.  There are other projects like OGV, Benchmark, and MOOSE that have their own documentation needs, may adopt their own antora or get integrated with this one, but aren't yet integrated well with the main repo docs, so "brlcad-docs" certainly isn't inappropriate.
